services:
    app:
        container_name: ${DOCKER_PREFIX_NAME}-app
        build:
            context: .
            dockerfile: compose/php/Dockerfile
            args:
                - UID=${DOCKER_UID:-1000}
                - GID=${DOCKER_GID:-1000}
                - XDEBUG_EXT=${DOCKER_XDEBUG_EXT:-false}
        volumes:
            - ./:/var/www/html
            - ./compose/log/supervisor:/var/log/supervisor
        networks:
            - local-network

networks:
    local-network:
        driver: bridge
